### PR TITLE
JSON schema no bigint strings

### PR DESCRIPTION
**Pull request by grant**
Fixes https://github.com/googleapis/google-cloudevents/issues/125

- For JSON schemas, uses `integer` instead of `string` for integer values.
  - For example CAL `port` field.
- Change in `examples` is due to a bug recorded here: https://github.com/googleapis/google-cloudevents/issues/126
  - Hopefully we can fix that before merging this PR.

### CODE REVIEW

**Review by jskeet — COMMENTED** [review]
This appears to capture the fact that it's an integer (good) but not the size... I can't see how the Java generator would generate int/Integer or long/Long properties based on this.

**Comment by grant** [comment]
To see how this change causes the Java generator to use a `Long` instead of a `string`, copy the updated JSON schema:

https://raw.githubusercontent.com/googleapis/google-cloudevents/grant_jsonschema_no_bigint_strings/jsonschema/google/events/cloud/audit/v1/LogEntryData.json

Paste it in `https://app.quicktype.io/`, ensuring the source type is JSON schema and language is Java (or Go).

The result is that this field is a `Long`/`int64`.

## Example

```java
/**
 * The log entry payload, which is always an AuditLog for Cloud Audit Log events.
 */
public class ProtoPayload {
    private AuthenticationInfo authenticationInfo;
    private AuthorizationInfo[] authorizationInfo;
    private Metadata metadata;
    private String methodName;
    private Long numResponseItems;  <---  Long!
    private Request request;
    private RequestMetadata requestMetadata;
    private ResourceLocation resourceLocation;
    private String resourceName;
    private ResourceOriginalState resourceOriginalState;
    private Response response;
    private ServiceData serviceData;
    private String serviceName;
    private Status status;
```

Ready for review.

**Review by jskeet — APPROVED** [review]
Okay, so this change *only* affects int64 fields... but it looks like we're using "integer" for int32 fields as well, e.g. for `StorageObjectData.component_count`. So that's still a problem IMO - just a different one to the one that's fixed here.

(In general, my main concern over the JSON schema is that it's losing a significant amount of type information.)

**Comment by grant** [comment]
Yes, I believe this only affects *64 proto fields.

Proto vs JSON schema based libraries is a language-per-language decision. If there are known caveats using the JSON schema description, such as int32 described above, that affects clients significantly, we should evaluate that per language.

**Comment by grant** [comment]
Merging this string int fix such that we can get on to other PRs.

**Pull request merged**
