### PR TITLE
Remove "envelope" protos

### PR DESCRIPTION
**Pull request by jskeet**
(First commit is from #11)

@yolocs @hrasadi

### CODE REVIEW

**Comment by yolocs** [comment]
I’m more leaning towards discussing this before removing. We obviously lack a place to put event types (markdown doesn’t appear to be the right place to me).

**Comment by yolocs** [comment]
Sorry I missed that you moved types to data messages. I don’t quite understand the reasoning behind. Could you explain?

**Comment by jskeet** [comment]
>  I don’t quite understand the reasoning behind. Could you explain?

Specifically so we would still have that information available, because it's useful information. This was what was suggested in the meeting yesterday.

I can see three options:

- Do more work to make the envelope messages more useful (e.g. with more concrete use cases, supported by libraries)
- Remove the envelope messages without moving the event types (remove the annotation itself for the moment)
- Go half way, as we have in this PR.

**Comment by jskeet** [comment]
> The CE dataschema which events should provide shoould point directly to the proto seen in the data field.

Yes, and that was always the expectation. The messages that are being removed here were always "nice to have for some use cases" rather than "the core messages every developer will need to use" - the latter being the `*Data` messages.

**Comment by jskeet** [comment]
Closing this PR as we have an alternative approach now: keep the protos themselves, but use proto file naming to allow selective generation. (Consumer libraries probably only need the data protos for now.)

**Pull request closed without merging**
