### PR TITLE
Rename fields in Firebase auth UserMetadata message

### PR DESCRIPTION
**Pull request by jskeet**
This allows them to conform with our API conventions better.
Functions Frameworks will need to perform appropriate conversions.

### CODE REVIEW

**Comment by jskeet** [comment]
Note: I *tried* to regenerate the JSON schema etc, but:

- Running ./scripts/gen.sh failed with an error I don't understand (see below)
- The regenerated JSON schema (which really *had* been regenerated) looked massively different from what we've got now, so I assume there are bigger problems

I'm running on Windows, which may well be the problem.

Output at the end of the failing scripts:

```text
Error: ENOENT: no such file or directory, open 'C:\users\jonskeet\GitHub\googleapis\google-cloudevents\tools\readme-catalog/../../jsonschema/catalog.json'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.<anonymous> (C:\users\jonskeet\GitHub\googleapis\google-cloudevents\tools\readme-catalog\index.js:6:31)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\users\\jonskeet\\GitHub\\googleapis\\google-cloudevents\\tools\\readme-catalog/../../jsonschema/catalog.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

**Comment by jskeet** [comment]
I've modified the schema manually, as it was just renaming two fields.

**Review by grant — APPROVED** [review]
LGTM. Sorry for the Windows path separator issue, can you file a separate bug for that?

**Comment by grant** [comment]
For the error, it's not resolving the `jsonschema/catalog.json` path.

**Comment by jskeet** [comment]
The weird thing is that I'm not sure that it's a path problem - but an earlier part of the script *deletes* that file, which I suspect is why it can't find it later. I haven't looked into it. Will file an issue shortly.

**Pull request merged**
