### PR TITLE
Event registry generation tool

### PR DESCRIPTION
**Pull request by jskeet**
This is very drafty - it's just the *kind* of thing we can do.

Sample output:

```text
google.cloud.audit.log.v1.written:
  Event message: google.events.cloud.audit.v1.AuditLogWrittenEvent
  Data message: google.events.cloud.audit.v1.AuditLogData
google.cloud.firestore.document.v1.created:
  Event message: google.events.cloud.firestore.v1.DocumentCreatedEvent
  Data message: google.events.cloud.firestore.v1.DocumentEventData
google.cloud.firestore.document.v1.updated:
  Event message: google.events.cloud.firestore.v1.DocumentUpdatedEvent
  Data message: google.events.cloud.firestore.v1.DocumentEventData
google.cloud.firestore.document.v1.deleted:
  Event message: google.events.cloud.firestore.v1.DocumentDeletedEvent
  Data message: google.events.cloud.firestore.v1.DocumentEventData
google.cloud.firestore.document.v1.written:
  Event message: google.events.cloud.firestore.v1.DocumentWrittenEvent
  Data message: google.events.cloud.firestore.v1.DocumentEventData
google.cloud.pubsub.topic.v1.messagePublished:
  Event message: google.events.cloud.pubsub.v1.MessagePublishedEvent
  Data message: google.events.cloud.pubsub.v1.MessagePublishedData
google.cloud.scheduler.job.v1.executed:
  Event message: google.events.cloud.scheduler.v1.JobExecutedEvent
  Data message: google.events.cloud.scheduler.v1.SchedulerData
google.cloud.storage.object.v1.finalized:
  Event message: google.events.cloud.storage.v1.ObjectFinalizedEvent
  Data message: google.events.cloud.storage.v1.StorageObjectData
google.cloud.storage.object.v1.archived:
  Event message: google.events.cloud.storage.v1.ObjectArchivedEvent
  Data message: google.events.cloud.storage.v1.StorageObjectData
google.cloud.storage.object.v1.deleted:
  Event message: google.events.cloud.storage.v1.ObjectDeletedEvent
  Data message: google.events.cloud.storage.v1.StorageObjectData
google.cloud.storage.object.v1.metadataUpdated:
  Event message: google.events.cloud.storage.v1.ObjectMetadataUpdatedEvent
  Data message: google.events.cloud.storage.v1.StorageObjectData
google.cloud.firebase.database.document.v1.created:
  Event message: google.events.firebase.v1.DocumentCreated
  Data message: google.events.firebase.v1.DocumentEventData
google.cloud.firebase.database.document.v1.updated:
  Event message: google.events.firebase.v1.DocumentUpdated
  Data message: google.events.firebase.v1.DocumentEventData
google.cloud.firebase.database.document.v1.deleted:
  Event message: google.events.firebase.v1.DocumentDeleted
  Data message: google.events.firebase.v1.DocumentEventData
google.cloud.firebase.database.document.v1.written:
  Event message: google.events.firebase.v1.DocumentWritten
  Data message: google.events.firebase.v1.DocumentEventData
```

### CODE REVIEW

**Comment by jskeet** [comment]
cc @grant

**Comment by grant** [comment]
Looks like a good start. Is there a GitHub issue for this?

I'd assume that language-specific code would be under the language-specific repo?
For example `.cs`, `.csproject`, `.sln` files.

Otherwise this repo will be a hodgepodge of every language right?

By separating by language, we can also separate concerns with language experts.

**Comment by jskeet** [comment]
> Looks like a good start. Is there a GitHub issue for this PR?

Not yet - I believe you were going to file one for discussion of exactly what we want from the tool :)

> I'd assume that language-specific code would be under the language-specific repo?

No - because it's not trying to provide .NET code to users. It's just a tool. It could be rewritten in any language, but it belongs in this repo because it's about the contents of the repo, not any specific language implementation.

> Otherwise this repo will be a hodgepodge of every language right?

I'd rather that than users have to look in seven different repos for tools that are fundamentally about the content of *this* repo. This tool isn't inherently about .NET - it's an implementation detail. It could be rewritten in Python to produce *exactly* the same output - it wouldn't make sense to move the code from one repo to another for that.

Additionally, I expect that once we've worked out exactly what format we want the event registry to be, it'll be included in a file (whether Markdown, JSON, both, or something similar) *in this repo* (as the source of truth for Google CloudEvents). I'd expect the CI job to regenerate it and fail if there's a difference between the regenerated version and what's in source control. That's far easier to do if the tool is in the same repo.

**Comment by jskeet** [comment]
Okay, let's think about what we might want in the README. It's easiest to do this here where GFM is available...

|Package|Event types|
|-|-|
|[google.events.cloud.firestore.v1](proto/google/events/cloud/firestore/v1)|google.cloud.firestore.document.v1.created<br/>google.cloud.firestore.document.v1.updated|
|[google.events.cloud.storage.v1](proto/google/events/cloud/storage/v1)|google.cloud.storage.object.v1.finalized<br/>google.cloud.storage.object.v1.deleted<br/>google.cloud.storage.object.v1.finalized|

The Markdown is ugly and long, but it looks reasonably pretty. Will implement now.

**Comment by jskeet** [comment]
If we want to go ahead with this, the next steps would probably be:

- Add a lot of comments to the code (and a README) - far more than I'd normally do - on the understanding that folks may want to tweak it without knowing C# (or at least without knowing C# well)
- Possibly run the code in CI and fail if it makes changes (so we know it's always up-to-date)

**Comment by grant** [comment]
Sounds good. Looking forward to this PR not being a draft.

**Comment by jskeet** [comment]
Great. Will add lots of comments on Monday, and make it non-draft and ready for review.

**Comment by jskeet** [comment]
Okay @grant, since you last looked:

- I've changed the C# code a little and added *lots* of comments. (I don't expect anyone with no C# background to be able to make very significant changes, but tweaks should be feasible.)
- Added more instructions in the README
- Added a consistency check as part of the Travis build, so the registry is guaranteed to be up-to-date

**Comment by jskeet** [comment]
Fixes #24.

**Pull request merged**
